version: "2"
linters:
  # Manually specify linters so we're not affected to changing defaults.
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - nolintlint
    - revive
    - staticcheck
    - unused
  settings:
    govet:
      # These govet checks are disabled by default, but they're useful.
      enable:
        - niliness
        - stringintcov
        - structtag
  exclusions:
    rules:
      # Don't warn on unused parameters.
      # # Parameter names are useful; replacing them with '_' is undesirable.
      - linters: [revive]
        text: 'unused-parameter: parameter \S+ seems to be unused, consider removing or renaming it as _'
formatters:
  enable:
    - gofumpt
    - goimports
