[tools]
go = "1.24"
golangci-lint = "v2.1.6"

[tasks.build]
description = "Build Go packages"
run = "go build ./..."

[tasks.test]
description = "Run Go tests"
run = "go test ./..."

[tasks.cover]
description = "Run Go tests with coverage"
run = "go test -coverprofile cover.out ./..."

[tasks.lint]
description = "Run golangci-lint"
run = "golangci-lint run ./..."

